[package]
name = "letsplay_gpu"
description = "GPU helpers and bindings for Let's Play"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
gl.workspace = true

[build-dependencies]
gl_generator.workspace = true
